apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ include "products.namespace" . }}
  labels:
    {{- include "products.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    {{- include "products.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
