{{- include "products.validatePostgresAuth" . -}}
{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "products.dbSecretName" . }}
  namespace: {{ include "products.namespace" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.name (.Values.postgres.service.port | int) .Values.postgres.auth.database | quote }}
{{- end }}
