apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
  namespace: products
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app_password
  POSTGRES_DB: products_db
  DATABASE_URL: postgresql://app:app_password@postgres:5432/products_db
